[tool.poetry]
name = "homework"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "isort (>=9.0.1,<10.0.0)",
    "mypy (>=2.3.1,<3.0.0)"
]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)"
]

[tool.black]
line-length = 88
target-version = ['py312']
exclude = '''
(?x)
    \.idea/
    | \.flake8/
    \ .Stuff/
'''

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.10"
strict = true
exclude = '''
(?x)
    \.idea/
    | \.flake8/
    \ .Stuff/
    \ README.md/
    \ Classroom/


'''


